# Custom evaluation template
# Extend this template for specific evaluation needs

model:
  type: text  # text, image, audio, multimodal
  name: custom_model
  batch_size: 8
  device: cuda:0
  parameters:
    # Add model-specific parameters
    temperature: 0.7
    max_tokens: 512
    top_p: 0.9
    # Add custom parameters
    custom_param1: value1
    custom_param2: value2

dataset:
  type: text  # text, image, audio, multimodal
  name: custom_dataset
  split: test
  max_samples: 1000
  batch_size: 8
  parameters:
    # Add dataset-specific parameters
    data_dir: data/custom
    file_format: json
    # Add custom parameters
    custom_param1: value1
    custom_param2: value2

evaluator:
  type: custom  # exact_match, regex, llm_judge, custom
  name: custom_evaluator
  parameters:
    # Add evaluator-specific parameters
    scoring_method: custom
    criteria:
      - criterion1
      - criterion2
    # Add custom parameters
    custom_param1: value1
    custom_param2: value2

metrics:
  - name: custom_metric1
    type: custom
    parameters:
      # Add metric-specific parameters
      threshold: 0.8
      # Add custom parameters
      custom_param1: value1
      custom_param2: value2
  
  - name: custom_metric2
    type: custom
    parameters:
      # Add metric-specific parameters
      weight: 0.5
      # Add custom parameters
      custom_param1: value1
      custom_param2: value2

output:
  formats: ["html", "json", "pdf"]
  save_predictions: true
  save_metrics: true
  save_error_analysis: true
  # Add custom output options
  custom_output1: value1
  custom_output2: value2

logging:
  level: INFO
  save_logs: true
  log_dir: logs
  # Add custom logging options
  custom_log1: value1
  custom_log2: value2

seed: 42

# Add custom sections as needed
custom_section:
  param1: value1
  param2: value2 